/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProfissionaisRouteImport } from './routes/profissionais'
import { Route as NoticiasRouteImport } from './routes/noticias'
import { Route as EscritorioRouteImport } from './routes/escritorio'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as AreasDeAtuacaoRouteImport } from './routes/areas-de-atuacao'
import { Route as AcidenteDeTrabalhoRouteImport } from './routes/acidente-de-trabalho'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NoticiasSlugRouteImport } from './routes/noticias.$slug'
import { Route as EquipeRenataHenriqueLeandroRouteImport } from './routes/equipe.renata-henrique-leandro'
import { Route as EquipeMariaInesGomesDaSilvaRouteImport } from './routes/equipe.maria-ines-gomes-da-silva'
import { Route as EquipeMarcioBarbosaDaSilvaRouteImport } from './routes/equipe.marcio-barbosa-da-silva'
import { Route as EquipeLeonardoNascimentoDeAguiarRouteImport } from './routes/equipe.leonardo-nascimento-de-aguiar'
import { Route as EquipeJuanAlbnerPereiraVelosoRouteImport } from './routes/equipe.juan-albner-pereira-veloso'
import { Route as EquipeJoaoTadeuLeandroRouteImport } from './routes/equipe.joao-tadeu-leandro'
import { Route as EquipeHigorHenriqueLeandroRouteImport } from './routes/equipe.higor-henrique-leandro'
import { Route as EquipeDenisonHenriqueLeandroRouteImport } from './routes/equipe.denison-henrique-leandro'
import { Route as EquipeDanielleCristinaMateusPereiraRouteImport } from './routes/equipe.danielle-cristina-mateus-pereira'
import { Route as AreasTrabalhistaRouteImport } from './routes/areas.trabalhista'
import { Route as AreasPrevidenciarioRouteImport } from './routes/areas.previdenciario'
import { Route as AreasMediacaoRouteImport } from './routes/areas.mediacao'
import { Route as AreasFamiliaRouteImport } from './routes/areas.familia'
import { Route as AreasContratosRouteImport } from './routes/areas.contratos'
import { Route as AreasConsumidorRouteImport } from './routes/areas.consumidor'
import { Route as AreasBancarioRouteImport } from './routes/areas.bancario'

const ProfissionaisRoute = ProfissionaisRouteImport.update({
  id: '/profissionais',
  path: '/profissionais',
  getParentRoute: () => rootRouteImport,
} as any)
const NoticiasRoute = NoticiasRouteImport.update({
  id: '/noticias',
  path: '/noticias',
  getParentRoute: () => rootRouteImport,
} as any)
const EscritorioRoute = EscritorioRouteImport.update({
  id: '/escritorio',
  path: '/escritorio',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const AreasDeAtuacaoRoute = AreasDeAtuacaoRouteImport.update({
  id: '/areas-de-atuacao',
  path: '/areas-de-atuacao',
  getParentRoute: () => rootRouteImport,
} as any)
const AcidenteDeTrabalhoRoute = AcidenteDeTrabalhoRouteImport.update({
  id: '/acidente-de-trabalho',
  path: '/acidente-de-trabalho',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NoticiasSlugRoute = NoticiasSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => NoticiasRoute,
} as any)
const EquipeRenataHenriqueLeandroRoute =
  EquipeRenataHenriqueLeandroRouteImport.update({
    id: '/equipe/renata-henrique-leandro',
    path: '/equipe/renata-henrique-leandro',
    getParentRoute: () => rootRouteImport,
  } as any)
const EquipeMariaInesGomesDaSilvaRoute =
  EquipeMariaInesGomesDaSilvaRouteImport.update({
    id: '/equipe/maria-ines-gomes-da-silva',
    path: '/equipe/maria-ines-gomes-da-silva',
    getParentRoute: () => rootRouteImport,
  } as any)
const EquipeMarcioBarbosaDaSilvaRoute =
  EquipeMarcioBarbosaDaSilvaRouteImport.update({
    id: '/equipe/marcio-barbosa-da-silva',
    path: '/equipe/marcio-barbosa-da-silva',
    getParentRoute: () => rootRouteImport,
  } as any)
const EquipeLeonardoNascimentoDeAguiarRoute =
  EquipeLeonardoNascimentoDeAguiarRouteImport.update({
    id: '/equipe/leonardo-nascimento-de-aguiar',
    path: '/equipe/leonardo-nascimento-de-aguiar',
    getParentRoute: () => rootRouteImport,
  } as any)
const EquipeJuanAlbnerPereiraVelosoRoute =
  EquipeJuanAlbnerPereiraVelosoRouteImport.update({
    id: '/equipe/juan-albner-pereira-veloso',
    path: '/equipe/juan-albner-pereira-veloso',
    getParentRoute: () => rootRouteImport,
  } as any)
const EquipeJoaoTadeuLeandroRoute = EquipeJoaoTadeuLeandroRouteImport.update({
  id: '/equipe/joao-tadeu-leandro',
  path: '/equipe/joao-tadeu-leandro',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipeHigorHenriqueLeandroRoute =
  EquipeHigorHenriqueLeandroRouteImport.update({
    id: '/equipe/higor-henrique-leandro',
    path: '/equipe/higor-henrique-leandro',
    getParentRoute: () => rootRouteImport,
  } as any)
const EquipeDenisonHenriqueLeandroRoute =
  EquipeDenisonHenriqueLeandroRouteImport.update({
    id: '/equipe/denison-henrique-leandro',
    path: '/equipe/denison-henrique-leandro',
    getParentRoute: () => rootRouteImport,
  } as any)
const EquipeDanielleCristinaMateusPereiraRoute =
  EquipeDanielleCristinaMateusPereiraRouteImport.update({
    id: '/equipe/danielle-cristina-mateus-pereira',
    path: '/equipe/danielle-cristina-mateus-pereira',
    getParentRoute: () => rootRouteImport,
  } as any)
const AreasTrabalhistaRoute = AreasTrabalhistaRouteImport.update({
  id: '/areas/trabalhista',
  path: '/areas/trabalhista',
  getParentRoute: () => rootRouteImport,
} as any)
const AreasPrevidenciarioRoute = AreasPrevidenciarioRouteImport.update({
  id: '/areas/previdenciario',
  path: '/areas/previdenciario',
  getParentRoute: () => rootRouteImport,
} as any)
const AreasMediacaoRoute = AreasMediacaoRouteImport.update({
  id: '/areas/mediacao',
  path: '/areas/mediacao',
  getParentRoute: () => rootRouteImport,
} as any)
const AreasFamiliaRoute = AreasFamiliaRouteImport.update({
  id: '/areas/familia',
  path: '/areas/familia',
  getParentRoute: () => rootRouteImport,
} as any)
const AreasContratosRoute = AreasContratosRouteImport.update({
  id: '/areas/contratos',
  path: '/areas/contratos',
  getParentRoute: () => rootRouteImport,
} as any)
const AreasConsumidorRoute = AreasConsumidorRouteImport.update({
  id: '/areas/consumidor',
  path: '/areas/consumidor',
  getParentRoute: () => rootRouteImport,
} as any)
const AreasBancarioRoute = AreasBancarioRouteImport.update({
  id: '/areas/bancario',
  path: '/areas/bancario',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/acidente-de-trabalho': typeof AcidenteDeTrabalhoRoute
  '/areas-de-atuacao': typeof AreasDeAtuacaoRoute
  '/contato': typeof ContatoRoute
  '/escritorio': typeof EscritorioRoute
  '/noticias': typeof NoticiasRouteWithChildren
  '/profissionais': typeof ProfissionaisRoute
  '/areas/bancario': typeof AreasBancarioRoute
  '/areas/consumidor': typeof AreasConsumidorRoute
  '/areas/contratos': typeof AreasContratosRoute
  '/areas/familia': typeof AreasFamiliaRoute
  '/areas/mediacao': typeof AreasMediacaoRoute
  '/areas/previdenciario': typeof AreasPrevidenciarioRoute
  '/areas/trabalhista': typeof AreasTrabalhistaRoute
  '/equipe/danielle-cristina-mateus-pereira': typeof EquipeDanielleCristinaMateusPereiraRoute
  '/equipe/denison-henrique-leandro': typeof EquipeDenisonHenriqueLeandroRoute
  '/equipe/higor-henrique-leandro': typeof EquipeHigorHenriqueLeandroRoute
  '/equipe/joao-tadeu-leandro': typeof EquipeJoaoTadeuLeandroRoute
  '/equipe/juan-albner-pereira-veloso': typeof EquipeJuanAlbnerPereiraVelosoRoute
  '/equipe/leonardo-nascimento-de-aguiar': typeof EquipeLeonardoNascimentoDeAguiarRoute
  '/equipe/marcio-barbosa-da-silva': typeof EquipeMarcioBarbosaDaSilvaRoute
  '/equipe/maria-ines-gomes-da-silva': typeof EquipeMariaInesGomesDaSilvaRoute
  '/equipe/renata-henrique-leandro': typeof EquipeRenataHenriqueLeandroRoute
  '/noticias/$slug': typeof NoticiasSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/acidente-de-trabalho': typeof AcidenteDeTrabalhoRoute
  '/areas-de-atuacao': typeof AreasDeAtuacaoRoute
  '/contato': typeof ContatoRoute
  '/escritorio': typeof EscritorioRoute
  '/noticias': typeof NoticiasRouteWithChildren
  '/profissionais': typeof ProfissionaisRoute
  '/areas/bancario': typeof AreasBancarioRoute
  '/areas/consumidor': typeof AreasConsumidorRoute
  '/areas/contratos': typeof AreasContratosRoute
  '/areas/familia': typeof AreasFamiliaRoute
  '/areas/mediacao': typeof AreasMediacaoRoute
  '/areas/previdenciario': typeof AreasPrevidenciarioRoute
  '/areas/trabalhista': typeof AreasTrabalhistaRoute
  '/equipe/danielle-cristina-mateus-pereira': typeof EquipeDanielleCristinaMateusPereiraRoute
  '/equipe/denison-henrique-leandro': typeof EquipeDenisonHenriqueLeandroRoute
  '/equipe/higor-henrique-leandro': typeof EquipeHigorHenriqueLeandroRoute
  '/equipe/joao-tadeu-leandro': typeof EquipeJoaoTadeuLeandroRoute
  '/equipe/juan-albner-pereira-veloso': typeof EquipeJuanAlbnerPereiraVelosoRoute
  '/equipe/leonardo-nascimento-de-aguiar': typeof EquipeLeonardoNascimentoDeAguiarRoute
  '/equipe/marcio-barbosa-da-silva': typeof EquipeMarcioBarbosaDaSilvaRoute
  '/equipe/maria-ines-gomes-da-silva': typeof EquipeMariaInesGomesDaSilvaRoute
  '/equipe/renata-henrique-leandro': typeof EquipeRenataHenriqueLeandroRoute
  '/noticias/$slug': typeof NoticiasSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/acidente-de-trabalho': typeof AcidenteDeTrabalhoRoute
  '/areas-de-atuacao': typeof AreasDeAtuacaoRoute
  '/contato': typeof ContatoRoute
  '/escritorio': typeof EscritorioRoute
  '/noticias': typeof NoticiasRouteWithChildren
  '/profissionais': typeof ProfissionaisRoute
  '/areas/bancario': typeof AreasBancarioRoute
  '/areas/consumidor': typeof AreasConsumidorRoute
  '/areas/contratos': typeof AreasContratosRoute
  '/areas/familia': typeof AreasFamiliaRoute
  '/areas/mediacao': typeof AreasMediacaoRoute
  '/areas/previdenciario': typeof AreasPrevidenciarioRoute
  '/areas/trabalhista': typeof AreasTrabalhistaRoute
  '/equipe/danielle-cristina-mateus-pereira': typeof EquipeDanielleCristinaMateusPereiraRoute
  '/equipe/denison-henrique-leandro': typeof EquipeDenisonHenriqueLeandroRoute
  '/equipe/higor-henrique-leandro': typeof EquipeHigorHenriqueLeandroRoute
  '/equipe/joao-tadeu-leandro': typeof EquipeJoaoTadeuLeandroRoute
  '/equipe/juan-albner-pereira-veloso': typeof EquipeJuanAlbnerPereiraVelosoRoute
  '/equipe/leonardo-nascimento-de-aguiar': typeof EquipeLeonardoNascimentoDeAguiarRoute
  '/equipe/marcio-barbosa-da-silva': typeof EquipeMarcioBarbosaDaSilvaRoute
  '/equipe/maria-ines-gomes-da-silva': typeof EquipeMariaInesGomesDaSilvaRoute
  '/equipe/renata-henrique-leandro': typeof EquipeRenataHenriqueLeandroRoute
  '/noticias/$slug': typeof NoticiasSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/acidente-de-trabalho'
    | '/areas-de-atuacao'
    | '/contato'
    | '/escritorio'
    | '/noticias'
    | '/profissionais'
    | '/areas/bancario'
    | '/areas/consumidor'
    | '/areas/contratos'
    | '/areas/familia'
    | '/areas/mediacao'
    | '/areas/previdenciario'
    | '/areas/trabalhista'
    | '/equipe/danielle-cristina-mateus-pereira'
    | '/equipe/denison-henrique-leandro'
    | '/equipe/higor-henrique-leandro'
    | '/equipe/joao-tadeu-leandro'
    | '/equipe/juan-albner-pereira-veloso'
    | '/equipe/leonardo-nascimento-de-aguiar'
    | '/equipe/marcio-barbosa-da-silva'
    | '/equipe/maria-ines-gomes-da-silva'
    | '/equipe/renata-henrique-leandro'
    | '/noticias/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/acidente-de-trabalho'
    | '/areas-de-atuacao'
    | '/contato'
    | '/escritorio'
    | '/noticias'
    | '/profissionais'
    | '/areas/bancario'
    | '/areas/consumidor'
    | '/areas/contratos'
    | '/areas/familia'
    | '/areas/mediacao'
    | '/areas/previdenciario'
    | '/areas/trabalhista'
    | '/equipe/danielle-cristina-mateus-pereira'
    | '/equipe/denison-henrique-leandro'
    | '/equipe/higor-henrique-leandro'
    | '/equipe/joao-tadeu-leandro'
    | '/equipe/juan-albner-pereira-veloso'
    | '/equipe/leonardo-nascimento-de-aguiar'
    | '/equipe/marcio-barbosa-da-silva'
    | '/equipe/maria-ines-gomes-da-silva'
    | '/equipe/renata-henrique-leandro'
    | '/noticias/$slug'
  id:
    | '__root__'
    | '/'
    | '/acidente-de-trabalho'
    | '/areas-de-atuacao'
    | '/contato'
    | '/escritorio'
    | '/noticias'
    | '/profissionais'
    | '/areas/bancario'
    | '/areas/consumidor'
    | '/areas/contratos'
    | '/areas/familia'
    | '/areas/mediacao'
    | '/areas/previdenciario'
    | '/areas/trabalhista'
    | '/equipe/danielle-cristina-mateus-pereira'
    | '/equipe/denison-henrique-leandro'
    | '/equipe/higor-henrique-leandro'
    | '/equipe/joao-tadeu-leandro'
    | '/equipe/juan-albner-pereira-veloso'
    | '/equipe/leonardo-nascimento-de-aguiar'
    | '/equipe/marcio-barbosa-da-silva'
    | '/equipe/maria-ines-gomes-da-silva'
    | '/equipe/renata-henrique-leandro'
    | '/noticias/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AcidenteDeTrabalhoRoute: typeof AcidenteDeTrabalhoRoute
  AreasDeAtuacaoRoute: typeof AreasDeAtuacaoRoute
  ContatoRoute: typeof ContatoRoute
  EscritorioRoute: typeof EscritorioRoute
  NoticiasRoute: typeof NoticiasRouteWithChildren
  ProfissionaisRoute: typeof ProfissionaisRoute
  AreasBancarioRoute: typeof AreasBancarioRoute
  AreasConsumidorRoute: typeof AreasConsumidorRoute
  AreasContratosRoute: typeof AreasContratosRoute
  AreasFamiliaRoute: typeof AreasFamiliaRoute
  AreasMediacaoRoute: typeof AreasMediacaoRoute
  AreasPrevidenciarioRoute: typeof AreasPrevidenciarioRoute
  AreasTrabalhistaRoute: typeof AreasTrabalhistaRoute
  EquipeDanielleCristinaMateusPereiraRoute: typeof EquipeDanielleCristinaMateusPereiraRoute
  EquipeDenisonHenriqueLeandroRoute: typeof EquipeDenisonHenriqueLeandroRoute
  EquipeHigorHenriqueLeandroRoute: typeof EquipeHigorHenriqueLeandroRoute
  EquipeJoaoTadeuLeandroRoute: typeof EquipeJoaoTadeuLeandroRoute
  EquipeJuanAlbnerPereiraVelosoRoute: typeof EquipeJuanAlbnerPereiraVelosoRoute
  EquipeLeonardoNascimentoDeAguiarRoute: typeof EquipeLeonardoNascimentoDeAguiarRoute
  EquipeMarcioBarbosaDaSilvaRoute: typeof EquipeMarcioBarbosaDaSilvaRoute
  EquipeMariaInesGomesDaSilvaRoute: typeof EquipeMariaInesGomesDaSilvaRoute
  EquipeRenataHenriqueLeandroRoute: typeof EquipeRenataHenriqueLeandroRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/profissionais': {
      id: '/profissionais'
      path: '/profissionais'
      fullPath: '/profissionais'
      preLoaderRoute: typeof ProfissionaisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/noticias': {
      id: '/noticias'
      path: '/noticias'
      fullPath: '/noticias'
      preLoaderRoute: typeof NoticiasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/escritorio': {
      id: '/escritorio'
      path: '/escritorio'
      fullPath: '/escritorio'
      preLoaderRoute: typeof EscritorioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/areas-de-atuacao': {
      id: '/areas-de-atuacao'
      path: '/areas-de-atuacao'
      fullPath: '/areas-de-atuacao'
      preLoaderRoute: typeof AreasDeAtuacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acidente-de-trabalho': {
      id: '/acidente-de-trabalho'
      path: '/acidente-de-trabalho'
      fullPath: '/acidente-de-trabalho'
      preLoaderRoute: typeof AcidenteDeTrabalhoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/noticias/$slug': {
      id: '/noticias/$slug'
      path: '/$slug'
      fullPath: '/noticias/$slug'
      preLoaderRoute: typeof NoticiasSlugRouteImport
      parentRoute: typeof NoticiasRoute
    }
    '/equipe/renata-henrique-leandro': {
      id: '/equipe/renata-henrique-leandro'
      path: '/equipe/renata-henrique-leandro'
      fullPath: '/equipe/renata-henrique-leandro'
      preLoaderRoute: typeof EquipeRenataHenriqueLeandroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipe/maria-ines-gomes-da-silva': {
      id: '/equipe/maria-ines-gomes-da-silva'
      path: '/equipe/maria-ines-gomes-da-silva'
      fullPath: '/equipe/maria-ines-gomes-da-silva'
      preLoaderRoute: typeof EquipeMariaInesGomesDaSilvaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipe/marcio-barbosa-da-silva': {
      id: '/equipe/marcio-barbosa-da-silva'
      path: '/equipe/marcio-barbosa-da-silva'
      fullPath: '/equipe/marcio-barbosa-da-silva'
      preLoaderRoute: typeof EquipeMarcioBarbosaDaSilvaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipe/leonardo-nascimento-de-aguiar': {
      id: '/equipe/leonardo-nascimento-de-aguiar'
      path: '/equipe/leonardo-nascimento-de-aguiar'
      fullPath: '/equipe/leonardo-nascimento-de-aguiar'
      preLoaderRoute: typeof EquipeLeonardoNascimentoDeAguiarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipe/juan-albner-pereira-veloso': {
      id: '/equipe/juan-albner-pereira-veloso'
      path: '/equipe/juan-albner-pereira-veloso'
      fullPath: '/equipe/juan-albner-pereira-veloso'
      preLoaderRoute: typeof EquipeJuanAlbnerPereiraVelosoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipe/joao-tadeu-leandro': {
      id: '/equipe/joao-tadeu-leandro'
      path: '/equipe/joao-tadeu-leandro'
      fullPath: '/equipe/joao-tadeu-leandro'
      preLoaderRoute: typeof EquipeJoaoTadeuLeandroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipe/higor-henrique-leandro': {
      id: '/equipe/higor-henrique-leandro'
      path: '/equipe/higor-henrique-leandro'
      fullPath: '/equipe/higor-henrique-leandro'
      preLoaderRoute: typeof EquipeHigorHenriqueLeandroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipe/denison-henrique-leandro': {
      id: '/equipe/denison-henrique-leandro'
      path: '/equipe/denison-henrique-leandro'
      fullPath: '/equipe/denison-henrique-leandro'
      preLoaderRoute: typeof EquipeDenisonHenriqueLeandroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipe/danielle-cristina-mateus-pereira': {
      id: '/equipe/danielle-cristina-mateus-pereira'
      path: '/equipe/danielle-cristina-mateus-pereira'
      fullPath: '/equipe/danielle-cristina-mateus-pereira'
      preLoaderRoute: typeof EquipeDanielleCristinaMateusPereiraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/areas/trabalhista': {
      id: '/areas/trabalhista'
      path: '/areas/trabalhista'
      fullPath: '/areas/trabalhista'
      preLoaderRoute: typeof AreasTrabalhistaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/areas/previdenciario': {
      id: '/areas/previdenciario'
      path: '/areas/previdenciario'
      fullPath: '/areas/previdenciario'
      preLoaderRoute: typeof AreasPrevidenciarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/areas/mediacao': {
      id: '/areas/mediacao'
      path: '/areas/mediacao'
      fullPath: '/areas/mediacao'
      preLoaderRoute: typeof AreasMediacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/areas/familia': {
      id: '/areas/familia'
      path: '/areas/familia'
      fullPath: '/areas/familia'
      preLoaderRoute: typeof AreasFamiliaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/areas/contratos': {
      id: '/areas/contratos'
      path: '/areas/contratos'
      fullPath: '/areas/contratos'
      preLoaderRoute: typeof AreasContratosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/areas/consumidor': {
      id: '/areas/consumidor'
      path: '/areas/consumidor'
      fullPath: '/areas/consumidor'
      preLoaderRoute: typeof AreasConsumidorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/areas/bancario': {
      id: '/areas/bancario'
      path: '/areas/bancario'
      fullPath: '/areas/bancario'
      preLoaderRoute: typeof AreasBancarioRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface NoticiasRouteChildren {
  NoticiasSlugRoute: typeof NoticiasSlugRoute
}

const NoticiasRouteChildren: NoticiasRouteChildren = {
  NoticiasSlugRoute: NoticiasSlugRoute,
}

const NoticiasRouteWithChildren = NoticiasRoute._addFileChildren(
  NoticiasRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AcidenteDeTrabalhoRoute: AcidenteDeTrabalhoRoute,
  AreasDeAtuacaoRoute: AreasDeAtuacaoRoute,
  ContatoRoute: ContatoRoute,
  EscritorioRoute: EscritorioRoute,
  NoticiasRoute: NoticiasRouteWithChildren,
  ProfissionaisRoute: ProfissionaisRoute,
  AreasBancarioRoute: AreasBancarioRoute,
  AreasConsumidorRoute: AreasConsumidorRoute,
  AreasContratosRoute: AreasContratosRoute,
  AreasFamiliaRoute: AreasFamiliaRoute,
  AreasMediacaoRoute: AreasMediacaoRoute,
  AreasPrevidenciarioRoute: AreasPrevidenciarioRoute,
  AreasTrabalhistaRoute: AreasTrabalhistaRoute,
  EquipeDanielleCristinaMateusPereiraRoute:
    EquipeDanielleCristinaMateusPereiraRoute,
  EquipeDenisonHenriqueLeandroRoute: EquipeDenisonHenriqueLeandroRoute,
  EquipeHigorHenriqueLeandroRoute: EquipeHigorHenriqueLeandroRoute,
  EquipeJoaoTadeuLeandroRoute: EquipeJoaoTadeuLeandroRoute,
  EquipeJuanAlbnerPereiraVelosoRoute: EquipeJuanAlbnerPereiraVelosoRoute,
  EquipeLeonardoNascimentoDeAguiarRoute: EquipeLeonardoNascimentoDeAguiarRoute,
  EquipeMarcioBarbosaDaSilvaRoute: EquipeMarcioBarbosaDaSilvaRoute,
  EquipeMariaInesGomesDaSilvaRoute: EquipeMariaInesGomesDaSilvaRoute,
  EquipeRenataHenriqueLeandroRoute: EquipeRenataHenriqueLeandroRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
