/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProfissionaisRouteImport } from './routes/profissionais'
import { Route as NoticiasRouteImport } from './routes/noticias'
import { Route as EscritorioRouteImport } from './routes/escritorio'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as AreasDeAtuacaoRouteImport } from './routes/areas-de-atuacao'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AreasTrabalhistaRouteImport } from './routes/areas.trabalhista'
import { Route as AreasPrevidenciarioRouteImport } from './routes/areas.previdenciario'
import { Route as AreasMediacaoRouteImport } from './routes/areas.mediacao'
import { Route as AreasFamiliaRouteImport } from './routes/areas.familia'
import { Route as AreasContratosRouteImport } from './routes/areas.contratos'
import { Route as AreasConsumidorRouteImport } from './routes/areas.consumidor'
import { Route as AreasBancarioRouteImport } from './routes/areas.bancario'

const ProfissionaisRoute = ProfissionaisRouteImport.update({
  id: '/profissionais',
  path: '/profissionais',
  getParentRoute: () => rootRouteImport,
} as any)
const NoticiasRoute = NoticiasRouteImport.update({
  id: '/noticias',
  path: '/noticias',
  getParentRoute: () => rootRouteImport,
} as any)
const EscritorioRoute = EscritorioRouteImport.update({
  id: '/escritorio',
  path: '/escritorio',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const AreasDeAtuacaoRoute = AreasDeAtuacaoRouteImport.update({
  id: '/areas-de-atuacao',
  path: '/areas-de-atuacao',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AreasTrabalhistaRoute = AreasTrabalhistaRouteImport.update({
  id: '/areas/trabalhista',
  path: '/areas/trabalhista',
  getParentRoute: () => rootRouteImport,
} as any)
const AreasPrevidenciarioRoute = AreasPrevidenciarioRouteImport.update({
  id: '/areas/previdenciario',
  path: '/areas/previdenciario',
  getParentRoute: () => rootRouteImport,
} as any)
const AreasMediacaoRoute = AreasMediacaoRouteImport.update({
  id: '/areas/mediacao',
  path: '/areas/mediacao',
  getParentRoute: () => rootRouteImport,
} as any)
const AreasFamiliaRoute = AreasFamiliaRouteImport.update({
  id: '/areas/familia',
  path: '/areas/familia',
  getParentRoute: () => rootRouteImport,
} as any)
const AreasContratosRoute = AreasContratosRouteImport.update({
  id: '/areas/contratos',
  path: '/areas/contratos',
  getParentRoute: () => rootRouteImport,
} as any)
const AreasConsumidorRoute = AreasConsumidorRouteImport.update({
  id: '/areas/consumidor',
  path: '/areas/consumidor',
  getParentRoute: () => rootRouteImport,
} as any)
const AreasBancarioRoute = AreasBancarioRouteImport.update({
  id: '/areas/bancario',
  path: '/areas/bancario',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/areas-de-atuacao': typeof AreasDeAtuacaoRoute
  '/contato': typeof ContatoRoute
  '/escritorio': typeof EscritorioRoute
  '/noticias': typeof NoticiasRoute
  '/profissionais': typeof ProfissionaisRoute
  '/areas/bancario': typeof AreasBancarioRoute
  '/areas/consumidor': typeof AreasConsumidorRoute
  '/areas/contratos': typeof AreasContratosRoute
  '/areas/familia': typeof AreasFamiliaRoute
  '/areas/mediacao': typeof AreasMediacaoRoute
  '/areas/previdenciario': typeof AreasPrevidenciarioRoute
  '/areas/trabalhista': typeof AreasTrabalhistaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/areas-de-atuacao': typeof AreasDeAtuacaoRoute
  '/contato': typeof ContatoRoute
  '/escritorio': typeof EscritorioRoute
  '/noticias': typeof NoticiasRoute
  '/profissionais': typeof ProfissionaisRoute
  '/areas/bancario': typeof AreasBancarioRoute
  '/areas/consumidor': typeof AreasConsumidorRoute
  '/areas/contratos': typeof AreasContratosRoute
  '/areas/familia': typeof AreasFamiliaRoute
  '/areas/mediacao': typeof AreasMediacaoRoute
  '/areas/previdenciario': typeof AreasPrevidenciarioRoute
  '/areas/trabalhista': typeof AreasTrabalhistaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/areas-de-atuacao': typeof AreasDeAtuacaoRoute
  '/contato': typeof ContatoRoute
  '/escritorio': typeof EscritorioRoute
  '/noticias': typeof NoticiasRoute
  '/profissionais': typeof ProfissionaisRoute
  '/areas/bancario': typeof AreasBancarioRoute
  '/areas/consumidor': typeof AreasConsumidorRoute
  '/areas/contratos': typeof AreasContratosRoute
  '/areas/familia': typeof AreasFamiliaRoute
  '/areas/mediacao': typeof AreasMediacaoRoute
  '/areas/previdenciario': typeof AreasPrevidenciarioRoute
  '/areas/trabalhista': typeof AreasTrabalhistaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/areas-de-atuacao'
    | '/contato'
    | '/escritorio'
    | '/noticias'
    | '/profissionais'
    | '/areas/bancario'
    | '/areas/consumidor'
    | '/areas/contratos'
    | '/areas/familia'
    | '/areas/mediacao'
    | '/areas/previdenciario'
    | '/areas/trabalhista'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/areas-de-atuacao'
    | '/contato'
    | '/escritorio'
    | '/noticias'
    | '/profissionais'
    | '/areas/bancario'
    | '/areas/consumidor'
    | '/areas/contratos'
    | '/areas/familia'
    | '/areas/mediacao'
    | '/areas/previdenciario'
    | '/areas/trabalhista'
  id:
    | '__root__'
    | '/'
    | '/areas-de-atuacao'
    | '/contato'
    | '/escritorio'
    | '/noticias'
    | '/profissionais'
    | '/areas/bancario'
    | '/areas/consumidor'
    | '/areas/contratos'
    | '/areas/familia'
    | '/areas/mediacao'
    | '/areas/previdenciario'
    | '/areas/trabalhista'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AreasDeAtuacaoRoute: typeof AreasDeAtuacaoRoute
  ContatoRoute: typeof ContatoRoute
  EscritorioRoute: typeof EscritorioRoute
  NoticiasRoute: typeof NoticiasRoute
  ProfissionaisRoute: typeof ProfissionaisRoute
  AreasBancarioRoute: typeof AreasBancarioRoute
  AreasConsumidorRoute: typeof AreasConsumidorRoute
  AreasContratosRoute: typeof AreasContratosRoute
  AreasFamiliaRoute: typeof AreasFamiliaRoute
  AreasMediacaoRoute: typeof AreasMediacaoRoute
  AreasPrevidenciarioRoute: typeof AreasPrevidenciarioRoute
  AreasTrabalhistaRoute: typeof AreasTrabalhistaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/profissionais': {
      id: '/profissionais'
      path: '/profissionais'
      fullPath: '/profissionais'
      preLoaderRoute: typeof ProfissionaisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/noticias': {
      id: '/noticias'
      path: '/noticias'
      fullPath: '/noticias'
      preLoaderRoute: typeof NoticiasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/escritorio': {
      id: '/escritorio'
      path: '/escritorio'
      fullPath: '/escritorio'
      preLoaderRoute: typeof EscritorioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/areas-de-atuacao': {
      id: '/areas-de-atuacao'
      path: '/areas-de-atuacao'
      fullPath: '/areas-de-atuacao'
      preLoaderRoute: typeof AreasDeAtuacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/areas/trabalhista': {
      id: '/areas/trabalhista'
      path: '/areas/trabalhista'
      fullPath: '/areas/trabalhista'
      preLoaderRoute: typeof AreasTrabalhistaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/areas/previdenciario': {
      id: '/areas/previdenciario'
      path: '/areas/previdenciario'
      fullPath: '/areas/previdenciario'
      preLoaderRoute: typeof AreasPrevidenciarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/areas/mediacao': {
      id: '/areas/mediacao'
      path: '/areas/mediacao'
      fullPath: '/areas/mediacao'
      preLoaderRoute: typeof AreasMediacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/areas/familia': {
      id: '/areas/familia'
      path: '/areas/familia'
      fullPath: '/areas/familia'
      preLoaderRoute: typeof AreasFamiliaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/areas/contratos': {
      id: '/areas/contratos'
      path: '/areas/contratos'
      fullPath: '/areas/contratos'
      preLoaderRoute: typeof AreasContratosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/areas/consumidor': {
      id: '/areas/consumidor'
      path: '/areas/consumidor'
      fullPath: '/areas/consumidor'
      preLoaderRoute: typeof AreasConsumidorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/areas/bancario': {
      id: '/areas/bancario'
      path: '/areas/bancario'
      fullPath: '/areas/bancario'
      preLoaderRoute: typeof AreasBancarioRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AreasDeAtuacaoRoute: AreasDeAtuacaoRoute,
  ContatoRoute: ContatoRoute,
  EscritorioRoute: EscritorioRoute,
  NoticiasRoute: NoticiasRoute,
  ProfissionaisRoute: ProfissionaisRoute,
  AreasBancarioRoute: AreasBancarioRoute,
  AreasConsumidorRoute: AreasConsumidorRoute,
  AreasContratosRoute: AreasContratosRoute,
  AreasFamiliaRoute: AreasFamiliaRoute,
  AreasMediacaoRoute: AreasMediacaoRoute,
  AreasPrevidenciarioRoute: AreasPrevidenciarioRoute,
  AreasTrabalhistaRoute: AreasTrabalhistaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
